language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t radu.rau/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true radu.rau/docker-react npm run test -- --coverage